### GET alle Produkte
GET http://localhost:8080/api/products
Accept: application/json

####### GET Produkt mit ID 
GET http://localhost:8080/api/products/1
Accept: application/json

###
### POST neues Produkt mit Bild (funktioniert in VS Code REST Client)
POST http://localhost:8080/api/products
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Testprodukt
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./access/images/4.jpg
--WebAppBoundary--

### Produkt mit ID löschen
DELETE http://localhost:8080/api/products/1
Accept: application/json
