
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    env_file:
      - .env
    environment:
      DEBUG: "true"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      LOGGING_LEVEL_ROOT: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      LOGGING_LEVEL_COM_EXAMPLE_MYCLOUD: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - backend

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
